### ISSUE TITLE
Set up python environment and 'hello world' CI

### ISSUE THREAD

**Issue by alisonrclarke** [DurhamARC/ManyFEWS#1]
Decide which environment manager to use - Django recommends pip so probably one of pip, pipenv, poetry.

Set up a basic CI for python.

**Comment by alisonrclarke** [comment]
poetry seems to be the tool of choice these days (assuming we want to avoid the heavyweight conda) so suggest we use that.

See https://python-poetry.org/docs/

https://github.com/marketplace/actions/python-poetry-action looks to be a well-maintained an popular Github Actions action for poetry.

**Comment by alisonrclarke** [comment]
We should also consider adding [black](https://black.readthedocs.io/en/stable/) to the project for easy consistent formatting.

**Comment by sjmf** [comment]
Closing as completed.
