### ISSUE TITLE
Create docker/docker-compose to do setup

### ISSUE THREAD

**Issue by alisonrclarke** [DurhamARC/ManyFEWS#43]
See e.g. https://docs.docker.com/samples/django/

(But we'll need to use postGIS in the db, and possibly need to add rabbit or Redis for celery.)

**Comment by sjmf** [comment]
The commit 1a03f4c addresses this issue, however, in production it is wise to run with a WSGI gateway (e.g. gunicorn) rather than the development server from Django. Leaving this issue open as details of production deployment need to be discussed with @simreaney and others.

**Comment by sjmf** [comment]
Dockerfile and docker-compose configs now exist and are finalised. Closing this issue.
